#!/bin/bash

copy_flag=0
compress_flag=0
ARCHIVE_DIR="$HOME/.archive/"

while [[ $1 == "-"* ]]
do
    case "$1" in
    --help | -h)
        echo "Usage: archive [OPTION] FILE..."
        echo "Copy/Move one or more files into archive directory ~/.archive"
        echo ""
        echo "Options:"
        echo "   -c     Copy files into archive directory"
        exit 0
        ;;
    --logs)
        cat $ARCHIVE_DIR.logs/*.log
        exit 0
        ;;
	-c)
	    copy_flag=1
        shift
	    ;;
    -z)
        compress_flag=1
        shift
        ;;
    *)
        break
        ;;
    esac
done

if [ $# -lt 1 ]
then
    echo "Usage: archive [OPTION] FILE..."
    echo "Copy/Move one or more files into archive directory ~/.archive"
    echo ""
    echo "Options:"
    echo "   -c     Copy files into archive directory"
    echo "   -z     Compress the file into a tar.gz file before archiving"
else
    while [ $# -gt 0 ]
    do
        file_name="$1"
        echo $file_name
        if [ $compress_flag -eq 1 ]
        then
            file_name="${1##*/}"
            file_name="$file_name-$(date +'%F-%H%M').tar.gz"
            err_out="$( tar zcf "$file_name" "$1" 2>&1 )"
            test $? -ne 0 || echo "$err_out" && exit $?
            err_out="$(mv $file_name $ARCHIVE_DIR 2>&1)"
            test $? -ne 0 || echo "$err_out" && exit $?
            
        elif [ $copy_flag -eq 1 ]
        then
            err_out="$(rsync -av $file_name $ARCHIVE_DIR 2>&1)"
            test $? -ne 0 || echo "$err_out" && exit $?
        else
            err_out="$(mv $file_name $ARCHIVE_DIR 2>&1)"
            test $? -ne 0 || echo "$err_out" && exit $?
        fi 
        echo "+'$file_name' $(date +'%b %d %Y %H:%M')" >> $ARCHIVE_DIR.logs/file_history.log
        shift
    done
fi
